name: "Create GitHub Repo"
description: "Creates a private repository based on the issue title"

inputs:
  org-admin-token:
    description: "GitHub Token with access to the organization"
    required: true

runs:
  using: "node12"
  main: "index.js"

outputs:
  repo-url:
    description: "The URL of the created repository"
